apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-04-20T07:28:27Z"
  labels:
    app: n1
  name: n1
  namespace: n2
  resourceVersion: "82082"
  uid: 804934fa-a80a-47fb-a7c2-64a6a8dae71b
spec:
  clusterIP: 10.233.15.196
  clusterIPs:
  - 10.233.15.196
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30630
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: n1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
