apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-04-20T06:43:52Z"
  generation: 1
  labels:
    app: n1
  name: n1
  namespace: default
  resourceVersion: "74630"
  uid: b2b6f713-3cc4-4809-a85c-22bd83dba388
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  conditions:
    - lastTransitionTime: "2023-04-20T06:44:01Z"
      lastUpdateTime: "2023-04-20T06:44:01Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-04-20T06:43:52Z"
      lastUpdateTime: "2023-04-20T06:44:01Z"
      message: ReplicaSet "n1-f5cb88c5c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing  
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: n1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: n1
    spec:
      containers:
      - image: nowage/mynginx:0.1
        imagePullPolicy: IfNotPresent
        name: mynginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
